### ISSUE TITLE
Doesn't work with Moment

### ISSUE THREAD

**Issue by Prior99** [Jimbly/timezone-mock#13]
This doesn't work well together with Moment. I have built a minimal reproduce:

```javascript
const moment = require('moment')
const a = moment().toDate();
// Will log the date.
console.log(a)

require('timezone-mock').register('UTC')
const b = moment().toDate();
// Will log `invalid date`.
console.log(b)
```

**Comment by Prior99** [comment]
I took a look at moments implementation of `toDate` and tracked this down to `valueOf` not being related, so perhaps this is fixed if #12 is fixed.

Is this actively being maintained? If I'd send a PR would you accept it?

**Comment by Jimbly** [comment]
Hi, depends what you mean by "actively maintained", as I haven't made time to look at these two issues, but a PR would be most welcome, I'll review it and as long as the unit tests pass I'll publish it to NPM =).

**Comment by Prior99** [comment]
Thank you :)

**Comment by Prior99** [comment]
Thank you.

**Comment by vegerot** [comment]
@Jimbly doesn't work for me.

Pretty much I have a test like 

```typescript
  it('should be utc >', () => {
    timezone_mock.register('Australia/Adelaide')
    vuetify = new Vuetify();
    store = MockStore();
    router = new VueRouter();

    setupIntersectionObserverMock();
    console.log(new Date())
    debugger

    wrapper = mount(SRTimelineDay, {
      localVue,
      propsData: {
        date: moment.utc(),
      },
      router,
      store,
      vuetify,
    });
    expect.assertions(1);
    //Accessing private member
    // @ts-expect-error 2341
    expect(wrapper.vm.localTimes).toStrictEqual(      ["20:00", "21:00", "22:00", "23:00", "00:00", "01:00", "02:00",
      "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00",
      "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00",
      "17:00", "18:00", "19:00"
    ])
    timezone_mock.unregister()

  })
```

And a function like this in my code

```typescript
const getLocalTimes = (): string[] => {
  const offsetHours: number = Math.floor(moment().utcOffset() / 60); // In case there is some non-hour offset
  let localTimes: string[] = [...zuluTimes];
  if (offsetHours < 0) {
    const tempTimes: string[] = localTimes.splice(offsetHours, offsetHours * -1);
    localTimes = [...tempTimes, ...localTimes];
  } else if (offsetHours > 0) {
    const tempTimes: string[] = localTimes.splice(0, offsetHours * -1);
    localTimes = [...localTimes, ...tempTimes];
  }
  debugger
  return localTimes;
};
```

Now, the problem is that the second `debugger` is ALWAYS called FIRST.  Meaning that it appears that `timezone_mock` is not called until after the tests.

Meaning that while debugging I first see
<img width="965" alt="image" src="https://user-images.githubusercontent.com/5297725/90659038-3da91000-e212-11ea-93e9-d675833e61fd.png">
(note the `offset`)

And then see 
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/5297725/90659291-7e088e00-e212-11ea-8714-ad1da5e7bc2a.png">

.

The `console.log` I have in the `it` only happens after the first debugger

**Comment by Jimbly** [comment]
@vegerot This doesn't sound like anything related to timezone-mock, it sounds like you're saying that your code is getting called before entering into your test?  You may want to check the callstack of where your code is getting called, and make sure it's only called within your tests or something.

**Comment by vegerot** [comment]
I am only running this single `it`.  I don't see how the code could be called from anywhere else

**Comment by vegerot** [comment]
Not sure how to interpret this call stack.  This is at the erroneous first breakpoint 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/5297725/90663401-9929cc80-e217-11ea-986b-37c6b25dcafa.png">

**Comment by Jimbly** [comment]
Looks like your code is perhaps being called inside of `require()`, perhaps module-scoped code that's being executed upon the require instead of in an exported function.  If that is desired, you need to move the require of your module to after the timezone_mock.register call to actually be affected by it.

**Comment by vegerot** [comment]
I do not use `require` for anything except this library.  Everything else uses ES6 imports

**Comment by Jimbly** [comment]
Sure, they're the same thing though, just different syntax - if you have code that runs in a global scope it gets run when you do `import foo`, so if you're doing the import before registering the mock, there's no possible way the code could used the mocked Date.
