### ISSUE TITLE
Error on empty string constructor: "Unhandled date format passed to MockDate constructor"

### ISSUE THREAD

**Issue by crazy4groovy** [Jimbly/timezone-mock#26]
https://github.com/Jimbly/timezone-mock/blob/master/index.js#L33

Can this lib support `new Date('')` just as native JavaScript does?

var d = new Date('')
d.toString() === "Invalid Date"
d.getHours() === NaN

(I am using the Yup lib for validation, and it is creating an invalid Date variable in its constructor. This is causing the error whenever I run tests.)

**Comment by Jimbly** [comment]
It could, but I'm not completely sure we would want it to.  This is, arguably, catching someone passing something incorrect/unhandled to a Date constructor, which is exactly what you'd want to find in tests.  However, the goal of this library is to just mock the timezone, not catch all Date-related errors, so that'd be a reasonable change.

It's probably just adding another `else` to that block, I think having `this.d = new Date('')` in that case will just pass through the NaNs appropriately.  If you want to make the change, I'd accept a PR with it and a test (just a couple new lines added to tests/test-constructors.js).

**Comment by Jimbly** [comment]
Resolved in #27.
