### ISSUE TITLE
needed `assert` in calcTZO?

### ISSUE THREAD

**Issue by crazy4groovy** [Jimbly/timezone-mock#33]
I'm having a deep lib issue between material-ui Calendar ---> date-fns-tz ---> timezone-mock.

https://github.com/Jimbly/timezone-mock/blob/master/index.js#L59

```
  ...
  assert.ok(false, ts);
  return 0;
}
```

Here `return 0;` seems like a reasonable statement at that point. But my unit tests are failing at the `assert`.

I think the `assert` line should be removed. (My unit tests pass when I do so in my local node_modules/). PR for this?

**Comment by crazy4groovy** [comment]
Note: `return 0;` was introduced in last release:
https://github.com/Jimbly/timezone-mock/commit/0d6ac1456dd776588a921813a084ebf7e71e3602#diff-168726dbe96b3ce427e7fedce31bb0bcR60

**Comment by Jimbly** [comment]
Assert is definitely needed, if that's being hit, you're probably using a timestamp that is outside of the range of times in tzdata.js, so it doesn't have any way to calculate whether it's in DST or not.  What's the timestamp that's throwing the assert, and what timezone are you mocking?

The return was just added to make the linter happy (I probably should have just added a //eslint-disable-line, since that's unreachable code).

**Comment by crazy4groovy** [comment]
Here's a screenshot of the stack trace:

![image](https://user-images.githubusercontent.com/1110812/74476390-3d047b00-4e77-11ea-8016-35ac91e22a6f.png)

IIRC, I believe... it has to do with `startOfMonth` being passed a `null`, which then eventually makes a `new Date(undefined)` down the line..

**Comment by Jimbly** [comment]
Ah, `ts` is `NaN`, which fails in `calcTZO`, I think `calcTZO` just needs a `if (isNaN(ts)) return 0;` or equivalent, as all of the local setters (`setDate` in this case) are just adding the return to NaN anyway, so doesn't really matter what it returns.
