### ISSUE TITLE
how to specify which date gets returned from new Date()

### ISSUE THREAD

**Issue by gregveres** [Jimbly/timezone-mock#55]
Hi, I am trying to unit test a call where I have a call to new Date();

I usually use the npm package mockdate to allow me to specify the specific date that I want to use for testing:
MockDate.set('...');

Then I can control the exact date that gets returned from new Date(). But I stumbled on this package because I need control over which timezone the system thinks it is in for when I do some cacluations on the date. For instance, I am doing a new Date() and then I need to extract the time of day in the browser local time. I know I need to test this code in multiple time zones, so timezone-mock seems to be a good option, but I can't figure out how timezone-mock would let me control the date that gets returned by new Date();

I also tried combining mockdate and timezone-mock like this:

```
import MockDate from 'mockdate';
import TimezoneMock from 'timezone-mock';
  beforeAll(() => {
    MockDate.set('2019-04-07T10:20:30Z');
    TimezoneMock.register('US/Eastern');
  });
  afterAll(() => {
    TimezoneMock.unregister();
  });

```

Before I put the TimezoneMock.register() call in the beforeAll, calling new Date() would return '2019-04-07T10:20:30Z', in my current timezone. But after I added the TimezoneMock.register(), new Date() reverted to returning today's date and in my current timezone, not in the specified timezone. 

Is there a way to have timezone-mock and mockdate work together?

**Comment by Jimbly** [comment]
Hi - you'd need to import `timezone-mock` *after* mocking the global `Date` with `MockDate`, e.g. something like so (might need to use the `require()` syntax instead of `import` though:
```javascript
  beforeAll(() => {
    import MockDate from 'mockdate';
    MockDate.set('2019-04-07T10:20:30Z');
    import TimezoneMock from 'timezone-mock';
    TimezoneMock.register('US/Eastern');
  });
  afterAll(() => {
    TimezoneMock.unregister();
  });
```

That being said, I don't think there's an good reason why this couldn't be made to work easily the way you have it written... try modifying `timezone-mock/index.js`'s `function register()` so that it re-grabs the global `Date` object each time while registering.  E.g. instead of just:
```javascript
glob.Date = MockDate;
```
it's this:
```javascript
if (glob.Date !== MockDate) { // protect in case `unregister()` wasn't called
  _Date = exports._Date = glob.Date;
}
glob.Date = MockDate
```

**Comment by gregveres** [comment]
Thanks for the suggestion. I was able to use a dynamic import of timezone-mock to get it to work.

**Comment by ctsstc** [comment]
I just had to call `MockDate.set` before `TimezoneMock` now tests are passing 🎉 

`setup-tests.ts`
```ts
import MockDate from 'mockdate'
import * as TimezoneMock from 'timezone-mock'

MockDate.set(new Date('2000-11-22T00:00:00.000Z'))
TimezoneMock.register('UTC')
```

**Comment by gregveres** [comment]
@ctsstc FYI, I have given up on timezone-mock. I am using jest's useFakeTimers that has been incorporated into, I think, v26 and later. 

I do something like this to mock the date:

```
beforeAll(() => {
    jest.useFakeTimers();
    jest.setSystemTime(new Date('2019-04-07T10:20:30Z'));
});
```

It works great and I don't have to have another package to install.

**Comment by Jimbly** [comment]
I believe #60 probably resolved this issue, it moved all of the global manipulation into `register()`-time code instead of `require()`-time code.

**Comment by ctsstc** [comment]
@gregveres Seems to be giving pain from importing a mock object imported from another file. I imagine because the `beforeAll` does not run before the import, thus the import is evaluated as a static object that instantiates a date object before it can import. To get around this though we could just change our code to be an evaluation that does not create the mock object until after we've been able to setup the system time utilizing your method.

## Problem Example

This example will have the proper mocked date in the test block but not in the `mockObj` that is imported.
I believe I also tried to do this `beforeAll` in a jest `setupFilesAfterEnv` which can utilize a `beforeAll` block, with no luck.

`mocks-file.ts`
```ts
export const mockObj = {
  id: 'abc123'
  createdAt: newDate()
}
```

`test.spec.ts`
```ts
import { mockObj } from './mocks-file.ts'

beforeAll(() => {
  jest.useFakeTimers()
  jest.setSystemTime(new Date('2000-11-22T00:00:00.000Z'))
})

it('has the right date and time', () => {
  const work = doWork(mockObject)
  
  expect(work).toEqual({
    id: 'abc123'
    createdAt: new Date()
  })
});
```

## Fix

In this scenario though we just need to instantiate the date after it's been mocked like so

`mocks-file.ts`
```ts
export const createMockObj = () => ({
  id: 'abc123'
  createdAt: newDate()
})
```

`test.spec.ts`
```ts
import { mockObj } from './mocks-file.ts'

beforeAll(() => {
  jest.useFakeTimers()
  jest.setSystemTime(new Date('2000-11-22T00:00:00.000Z'))
})

it('has the right date and time', () => {
  const mockObject = createMockObj()
  const work = doWork(mockObject)
  
  expect(work).toEqual({
    id: 'abc123'
    createdAt: new Date()
  })
});
```

**Comment by et** [comment]
@gregveres - For the code you provided, how are you handling switching the timezone dynamically in tests?
