### ISSUE TITLE
Add support for `mm/dd/yyyy`

### ISSUE THREAD

**Issue by AnimeAllstar** [Jimbly/timezone-mock#70]
Should't `mm/dd/yyyy` be a valid date? https://www.typescriptlang.org/play/?ssl=1&ssc=40&pln=1&pc=50#code/MYewdgziA2CmB00QHMAUZYHcAEARAhgC6yoBEAjAAwD0AzDQEyUMAspAlO9tddgLZ9qAEyHUAnhLEAoUJBgIkaDDgLEy9alWpNWHLj2wjqA8ZKA

I get the following error when I try to use `mm/dd/yyyy`:

```
Error: Uncaught [AssertionError: Unhandled date format passed to MockDate constructor: 10/1/2024]
```

I would expect the mock Date object to behave in the same manner that the actual Date object behaves.

**Comment by Jimbly** [comment]
Debatably, but I'd say no, that's exactly the kind of bug this library is trying to catch (depending on the locale of the computer/browser running that code, `10/1/2024` may be interpreted as Oct 1st, or Jan 10th).

**Comment by Jimbly** [comment]
If you've actually got code that's expecting a timezone/locale-specific date format to be parsed in the current locale (e.g. user input validation), then maybe the code isn't a "bug" - not sure if it's something this should generally allow through though, may be easier to unregister and register the mock around the particular test if it's an exceptional case like that.

If there's a really good reason for it, I'm open to a PR to support it though (even if maybe should only be opted into, not allowed by default).

**Comment by AnimeAllstar** [comment]
I think given that `new Date("1/30/2024").toLocaleDateString()` returns `1/30/2024` (https://www.typescriptlang.org/play/?#code/MYewdgziA2CmB00QHMAUZYHcAEARAhgC6yoBEAjAPQDMADJQEy0MAspAlPISADIjD44BYgGVCAJwCWYNO3ZA) and `1/30/2024` is considered a valid date, I think we should add an option (maybe using `mockDateOptions`) to provide support for `mm/dd/yyyy`.

**Comment by Jimbly** [comment]
Depending on my browser's locale, `new Date("1/30/2024").toLocaleDateString()` returns either `1/30/2024` or `Invalid Date` or `30.1.2024` here.

`yyyy-mm-dd` is defined in the JavaScript spec as a _UTC_ timestamp (note that `new Date('2024-01-30').toLocaleDateString()` will return `1/29/2024` in many time zones, *not* `1/30/2024`).
There's also the format `yyyy-mm-dd hh:mm`, which is also defined by the spec to be a (timezone) local time in that specific format (month-first).

However, `##/##/yyyy` is ambiguous, it's _not_ defined as to whether or not the first parameter is a month or a day, that's up to the locale, and will get converted to a locale string also depending on the locale, which means `new Date('1/10/2024').toLocaleDateString()` may return yet different things like `10.1.2024` or `1.10.2024` depending on the locale.  I think any way we look at this, you've probably got a test which is going to fail when ran on someone's computer that's in particular other locales.  Since timezone-mock does _not_ mock locales, only timezones, any timezone-related logic it's doing is potentially going to be wrong.

Looking at the code, it appears there's already a `fallbackFn` parameter, so if you really know what you're doing and still want to parse ambiguous dates, perhaps try adding something like this to the registration (I'm not 100% this is right, you might have to tinker with it):
```js
  fallbackFn: (str) => {
    let a = new timezone_mock._Date(str);
    assert(isFinite(a.getTime());
    let offset = new Date().calcTZO(a.getTime());
    return new timezone_mock._Date(a.getTime() + offset);
  }
``

**Comment by AnimeAllstar** [comment]
Hey, I spent some more time looking at this, and you were right. This is a bug and we should not be using the output of `.toLocaleDateString()` to initialize a date object.

**Comment by Jimbly** [comment]
Glad to hear that the library (or my comments) helped find a bug =).  Too bad dates in JavaScript are so terrible 😅.
